//! Amendment 2 (ii) test 2 (`AUDIT/ojas-training-2026-10-01/fable-rung-b-bars.md` Q2): the
//! per-entry AdamW golden at a pre-registered, decay-sensitive setting, consumed through the
//! trainer's own path.
//!
//! L-oracle built the golden through F's builder (`layerwise_param_groups` + `build_optimizer`,
//! `MasterWeightAdamW`), at lr 1e-2, 5 steps and the 8 x 0.1 split. Pre-registered in
//! `preregistration.json` before it ran; generated by `tools/qd_train_oracle_adamw.py`. Its 19
//! entries carry the decay targets (norms, `dt_bias`, a GDN gated norm, a `q_norm`), one tower
//! entry with no gradient on any step, and a span head with gradients on steps 1, 3 and 5 only.
//!
//! The trainer's path is the one tested:
//! - [`recipe::optimizer_table`] builds the per-entry `(lr_scale, weight_decay, eps, betas)`
//!   from the names;
//! - [`adamw_entry_step`] steps each entry: skipped on a `None` gradient, bias-corrected on its
//!   own count, decayed at its own scaled rate. The loop calls the same function for every
//!   host entry (`trainer.rs`).
//!
//! On the device the tower's update is tessl's `qwen35_adamw`, which needs per-entry `lr_scale`
//! before this setting can run there.
//!
//! The bound is the pre-registration's: 1e-6 absolute per element, over every step and entry,
//! on the fp32 master.

mod common;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use qd_export::safetensors::{Dtype, SafeTensorsFile};
use qd_train::adamw::{adamw_entry_step, EntryState};
use qd_train::recipe::{self, optimizer_table, EntryHyper, LowerLayers, OptimizerRecipe};
use qd_train::step::ParamSpec;
use serde_json::Value;

const HEAD_PREFIX: &str = "span_head.";

fn dir() -> PathBuf {
    common::crate_dir().join("tests/fixtures/adamw-decay-sensitive")
}

fn json(path: &Path) -> Value {
    serde_json::from_str(&std::fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display())))
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The manifest, after every file it pins has been checked against its pin (sha256 and byte
/// count, through the shared `common::pins` check, which also refuses a file it does not list):
/// nothing below is read from a file whose bytes are not the generator's.
fn pinned_manifest() -> Value {
    let dir = common::pins::verified(&dir(), common::pins::Form::JsonFiles);
    let m = json(&dir.join(common::pins::MANIFEST_JSON));
    let files = m["files"].as_object().expect("manifest.files");
    let want = ["golden.safetensors", "inputs.safetensors", "preregistration.json", "table.json"];
    assert_eq!(files.keys().map(String::as_str).collect::<Vec<_>>(), want, "the manifest pins exactly these files");
    assert_eq!(
        m["preregistration"]["sha256"], files["preregistration.json"]["sha256"],
        "the golden was generated from the pre-registration that is committed"
    );
    m
}

/// Every tensor of a safetensors file, f32 only (the golden's dtype for inputs and outputs).
fn tensors(path: &Path) -> BTreeMap<String, Vec<f32>> {
    let file = SafeTensorsFile::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    file.tensors()
        .iter()
        .map(|(name, info)| {
            assert_eq!(info.dtype, Dtype::F32, "{name}");
            let n: usize = info.shape.iter().product();
            let mut b = vec![0u8; n * 4];
            file.read_tensor_range(info, 0, &mut b).unwrap();
            (name.clone(), b.as_chunks::<4>().0.iter().map(|c| f32::from_le_bytes(*c)).collect())
        })
        .collect()
}

struct Golden {
    /// `(name, shape, grad_steps)` in the pre-registration's order.
    entries: Vec<(String, Vec<usize>, Vec<u64>)>,
    lr: f64,
    steps: u64,
    recipe: OptimizerRecipe,
    table: Value,
    inputs: BTreeMap<String, Vec<f32>>,
    golden: BTreeMap<String, Vec<f32>>,
    bound: f64,
}

fn load() -> Golden {
    let m = pinned_manifest();
    let pre = json(&dir().join("preregistration.json"));
    let entries = pre["entries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            let shape = e["shape"].as_array().unwrap().iter().map(|d| d.as_u64().unwrap() as usize).collect();
            let steps = e["grad_steps"].as_array().unwrap().iter().map(|s| s.as_u64().unwrap()).collect();
            (e["name"].as_str().unwrap().to_owned(), shape, steps)
        })
        .collect();
    // F's split (`--lower-layers-n 8 --lower-layers-lr-scale 0.1`, default beta2), typed here
    // as the trainer's CLI would be given it and checked against what the builder was run at.
    let o = &m["optimizer"];
    let recipe = OptimizerRecipe {
        lr: 1e-2,
        beta2: recipe::DEFAULT_BETA2,
        lower_layers: Some(LowerLayers { n: 8, lr_scale: 0.1 }),
    };
    assert_eq!(o["lr"].as_f64(), Some(recipe.lr));
    assert_eq!(pre["settings"]["lr"].as_f64(), Some(recipe.lr));
    assert_eq!(o["lower_layers_n"].as_u64(), Some(8));
    assert_eq!(o["lower_lr_scale"].as_f64(), Some(0.1));
    assert_eq!(o["beta2"].as_f64(), Some(recipe.beta2));
    assert_eq!(o["class"], "qd_train.optim.MasterWeightAdamW");
    let steps = o["steps"].as_u64().unwrap();
    assert_eq!(pre["settings"]["steps"].as_u64(), Some(steps));
    let bound = m["measure"]["bound"].as_f64().unwrap();
    assert_eq!(pre["measure"]["bound"].as_f64(), Some(bound));
    Golden {
        entries,
        lr: recipe.lr,
        steps,
        recipe,
        table: json(&dir().join("table.json")),
        inputs: tensors(&dir().join("inputs.safetensors")),
        golden: tensors(&dir().join("golden.safetensors")),
        bound,
    }
}

/// The trainer's table for the golden's entries: tower entries as the provider's, in the
/// golden's order, then the span head as host entries under the head's own bare names. Keyed by
/// the golden's names.
fn trainer_table(g: &Golden) -> BTreeMap<String, EntryHyper> {
    let spec = |(name, shape, _): &(String, Vec<usize>, Vec<u64>)| ParamSpec::new(name, shape);
    let tower: Vec<ParamSpec> = g.entries.iter().filter(|e| !e.0.starts_with(HEAD_PREFIX)).map(spec).collect();
    let head: Vec<ParamSpec> = g
        .entries
        .iter()
        .filter(|e| e.0.starts_with(HEAD_PREFIX))
        .map(|e| ParamSpec::new(e.0.trim_start_matches(HEAD_PREFIX), &e.1))
        .collect();
    assert_eq!((tower.len(), head.len()), (15, 4));
    let rows = optimizer_table(&tower, &head, &g.recipe).expect("F's recipe builds a table on these names");
    rows.into_iter()
        .enumerate()
        .map(|(i, r)| {
            let key = if i < tower.len() { r.name.clone() } else { format!("{HEAD_PREFIX}{}", r.name) };
            (key, r)
        })
        .collect()
}

/// What the trainer's path produces, step by step, against the golden.
struct Outcome {
    max_abs: f64,
    at: (u64, String),
    elements: u64,
    bit_identical: u64,
    moments_max_abs: f64,
    steps_taken: BTreeMap<String, u64>,
}

fn run(g: &Golden, table: &BTreeMap<String, EntryHyper>) -> Outcome {
    let mut values: BTreeMap<&str, Vec<f32>> = BTreeMap::new();
    let mut state: BTreeMap<&str, EntryState> = BTreeMap::new();
    for (name, shape, _) in &g.entries {
        let init = g.inputs[&format!("init.{name}")].clone();
        assert_eq!(init.len(), shape.iter().product::<usize>(), "{name}");
        state.insert(name, EntryState::zeros(init.len()));
        values.insert(name, init);
    }
    let mut out = Outcome {
        max_abs: 0.0,
        at: (0, String::new()),
        elements: 0,
        bit_identical: 0,
        moments_max_abs: 0.0,
        steps_taken: BTreeMap::new(),
    };
    for t in 1..=g.steps {
        for (name, _, grad_steps) in &g.entries {
            let grad = g.inputs.get(&format!("grad.step{t}.{name}"));
            assert_eq!(grad.is_some(), grad_steps.contains(&t), "{name} step {t}: the inputs and the pre-registration agree");
            let before = values[name.as_str()].clone();
            let v = values.get_mut(name.as_str()).unwrap();
            let s = state.get_mut(name.as_str()).unwrap();
            let stepped = adamw_entry_step(v, grad.map(Vec::as_slice), s, &table[name], g.lr, 1.0).unwrap();
            assert_eq!(stepped, grad.is_some());
            if !stepped {
                assert_eq!(*v, before, "{name} step {t}: no gradient, so no decay and no move");
            }
            let want = &g.golden[&format!("w.step{t}.{name}")];
            assert_eq!(want.len(), v.len(), "{name}");
            for (a, b) in v.iter().zip(want) {
                let d = f64::from((a - b).abs());
                out.elements += 1;
                out.bit_identical += u64::from(a.to_bits() == b.to_bits());
                if d > out.max_abs {
                    out.max_abs = d;
                    out.at = (t, name.clone());
                }
            }
            // The moments: present in the golden once the entry has stepped. Report-only beside
            // the pre-registered weight measure, except that presence must agree.
            let m = g.golden.get(&format!("exp_avg.step{t}.{name}"));
            let sq = g.golden.get(&format!("exp_avg_sq.step{t}.{name}"));
            assert_eq!(m.is_some(), s.steps > 0, "{name} step {t}: torch has moments exactly when the entry has stepped");
            if let (Some(m), Some(sq)) = (m, sq) {
                for (a, b) in s.moments.m.iter().zip(m).chain(s.moments.v.iter().zip(sq)) {
                    out.moments_max_abs = out.moments_max_abs.max(f64::from((a - b).abs()));
                }
            }
        }
    }
    out.steps_taken = state.into_iter().map(|(n, s)| (n.to_owned(), s.steps)).collect();
    out
}

#[test]
fn the_trainers_table_is_fs_builders_on_the_goldens_entries() {
    let g = load();
    let table = trainer_table(&g);
    let want = g.table.as_object().unwrap();
    assert_eq!(table.keys().collect::<Vec<_>>(), want.keys().collect::<Vec<_>>(), "the same 19 names");
    for (name, row) in &table {
        let w = &want[name];
        let got = [row.lr_scale, row.weight_decay, row.eps, row.beta1, row.beta2].map(f64::to_bits);
        let exp = [
            w["lr_scale"].as_f64().unwrap(),
            w["weight_decay"].as_f64().unwrap(),
            w["eps"].as_f64().unwrap(),
            w["betas"][0].as_f64().unwrap(),
            w["betas"][1].as_f64().unwrap(),
        ]
        .map(f64::to_bits);
        assert_eq!(got, exp, "{name}: (lr_scale, weight_decay, eps, beta1, beta2)");
    }
    // The pre-registered decay targets really are decayed, and the 0.1 group really is scaled.
    let excluded: Vec<&String> = want.iter().filter(|(_, w)| w["tessl_default_excludes"] == true).map(|(n, _)| n).collect();
    assert!(excluded.len() >= 6, "{excluded:?}");
    assert!(excluded.iter().all(|n| table[*n].weight_decay == recipe::WEIGHT_DECAY));
    assert_eq!(table.values().filter(|r| r.lr_scale == 0.1).count(), 8, "layers 0, 3 and 7's entries");
}

#[test]
fn the_trainers_entry_step_reproduces_the_golden_within_the_preregistered_bound() {
    let g = load();
    let table = trainer_table(&g);
    let out = run(&g, &table);
    eprintln!(
        "adamw-decay-sensitive: max |w - golden| = {:e} at step {} {} (bound {:e}); {} of {} elements bit-identical; \
         moments max |d| = {:e} (report-only)",
        out.max_abs, out.at.0, out.at.1, g.bound, out.bit_identical, out.elements, out.moments_max_abs
    );
    let per_step: u64 = g.entries.iter().map(|e| e.1.iter().product::<usize>() as u64).sum();
    assert_eq!(per_step, 214, "the 19 entries' elements");
    assert_eq!(out.elements, g.steps * per_step, "every element of every step was measured");
    assert!(out.max_abs <= g.bound, "max |w - golden| {:e} at step {} {} is over {:e}", out.max_abs, out.at.0, out.at.1, g.bound);
    // Each entry's own count is torch's `state["step"]` after the run.
    for (name, taken) in &out.steps_taken {
        assert_eq!(Some(*taken), g.table[name]["adamw_steps_taken"].as_u64(), "{name}: AdamW steps taken");
    }
    assert_eq!(out.steps_taken["layers.23.mlp.up_proj.weight"], 0);
    assert_eq!(out.steps_taken["span_head.start_proj.weight"], 3);
    assert_eq!(out.steps_taken["norm.weight"], 5);
}
