//! Amendment 2 (iv): the span-head init is pinned by its file's sha256 and by the repo's tensor-set
//! digest (`run_control._sidecar_digest` over `qd-tensor-ref-v1`), and the trainer refuses a
//! file that matches neither or only one.
//!
//! The digest port is checked against Python's own functions on the tiny head (the `span_head.*`
//! tensors of rung (b)'s `tiny-published/init.safetensors`), which
//! `tools/qd_train_oracle_head_digest.py` dumped to `fixtures/span-head-init-digest-tiny.json`.
//!
//! L-oracle's init files are loaded under their manifests' pins:
//! - the 64-wide one is tracked (`span-head-init-seed0-h64.*`), and always runs;
//! - the 2048-wide one is not tracked (`data/checkpoints/span-head-init/`, regenerated by the
//!   lead). Its test is `#[ignore]` and takes the file from `QD_SPAN_HEAD_INIT_2B`, refusing to
//!   pass without it.

mod common;

use std::path::{Path, PathBuf};

use qd_export::safetensors::{Dtype, PlannedTensor, SafeTensorsFile, Writer};
use qd_train::ft_data::{load_span_head_pinned, span_head_content_digest, HeadInitPin};
use qd_train::run_control::{sidecar_digest, tensor_ref_digest};
use qd_train::span_head::SpanHead;
use qd_train::trainer::TrainError;
use serde_json::Value;
use sha2::{Digest, Sha256};

fn fixtures() -> PathBuf {
    common::crate_dir().join("tests/fixtures")
}

fn oracle() -> Value {
    serde_json::from_str(&std::fs::read_to_string(fixtures().join("span-head-init-digest-tiny.json")).unwrap()).unwrap()
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// The tiny init's four `span_head.*` tensors: (name, shape, little-endian bytes).
fn tiny_head_tensors() -> Vec<(String, Vec<usize>, Vec<u8>)> {
    let file = SafeTensorsFile::open(&fixtures().join("tiny-published/init.safetensors")).unwrap();
    let mut out = Vec::new();
    for (name, info) in file.tensors() {
        if !name.starts_with("span_head.") {
            continue;
        }
        assert_eq!(info.dtype, Dtype::F32, "{name}");
        let mut bytes = vec![0u8; info.shape.iter().product::<usize>() * 4];
        file.read_tensor_range(info, 0, &mut bytes).unwrap();
        out.push((name.clone(), info.shape.clone(), bytes));
    }
    out
}

fn floats(b: &[u8]) -> Vec<f32> {
    b.as_chunks::<4>().0.iter().map(|c| f32::from_le_bytes(*c)).collect()
}

fn tiny_head() -> SpanHead {
    let t = tiny_head_tensors();
    let get = |n: &str| floats(&t.iter().find(|(name, _, _)| name == n).unwrap().2);
    SpanHead::new(
        64,
        get("span_head.start_proj.weight"),
        get("span_head.end_proj.weight"),
        get("span_head.abstain_start"),
        get("span_head.abstain_end"),
    )
    .unwrap()
}

#[test]
fn the_tensor_set_digest_is_pythons_on_the_tiny_head() {
    let o = oracle();
    let src = std::fs::read(fixtures().join("tiny-published/init.safetensors")).unwrap();
    assert_eq!(hex(&Sha256::digest(&src)), o["source_sha256"].as_str().unwrap(), "the fixture's source file");
    let tensors = tiny_head_tensors();
    assert_eq!(tensors.len(), 4);
    let mut refs = Vec::new();
    for (name, shape, bytes) in &tensors {
        let want = &o["tensors"][name];
        assert_eq!(want["dtype"], "float32");
        let d = tensor_ref_digest("float32", shape, 4, bytes).unwrap();
        assert_eq!(d, want["digest"].as_str().unwrap(), "{name}: TensorRef.digest");
        refs.push((name.clone(), d));
    }
    let want = o["content_digest"].as_str().unwrap();
    assert_eq!(sidecar_digest(&refs).unwrap(), want, "_sidecar_digest");
    // The same digest from the head as the trainer holds it.
    assert_eq!(span_head_content_digest(&tiny_head()).unwrap(), want);
    // What the port refuses rather than hashes.
    assert!(tensor_ref_digest("float32", &[64], 4, &[0u8; 255]).is_err(), "a byte count off its shape");
    let dup = vec![refs[0].clone(), refs[0].clone()];
    assert!(sidecar_digest(&dup).is_err(), "a name twice");
    let bad = vec![(refs[0].0.clone(), "AB".repeat(32))];
    assert!(sidecar_digest(&bad).is_err(), "an upper-case digest is not one this code writes");
}

/// The tiny head as a head-only init file (all four under `span_head.`, f32), as L-oracle's
/// 2048-wide file is laid out; returns its sha256.
fn write_head(path: &Path, head: &SpanHead) -> String {
    let h = head.hidden_size();
    let plan: Vec<PlannedTensor> = head
        .named()
        .iter()
        .map(|(n, _)| PlannedTensor {
            name: format!("span_head.{n}"),
            dtype: Dtype::F32,
            shape: if n.ends_with(".weight") { vec![h, h] } else { vec![h] },
        })
        .collect();
    let mut w = Writer::create(path, plan).unwrap();
    for p in w.order() {
        let short = p.name.strip_prefix("span_head.").unwrap();
        let (_, values) = head.named().into_iter().find(|(n, _)| *n == short).unwrap();
        let bytes: Vec<u8> = values.iter().flat_map(|v| v.to_le_bytes()).collect();
        w.begin(&p.name).unwrap();
        w.write(&bytes).unwrap();
        w.end().unwrap();
    }
    hex(&w.finish().unwrap().sha256)
}

#[test]
fn a_pinned_head_init_loads_and_any_mismatch_is_refused() {
    let o = oracle();
    let content = o["content_digest"].as_str().unwrap().to_owned();
    let dir = common::scratch("head-init");
    let path = dir.join("span_head_init-tiny.safetensors");
    let head = tiny_head();
    let sha = write_head(&path, &head);
    assert_eq!(sha, hex(&Sha256::digest(std::fs::read(&path).unwrap())));
    let pin = HeadInitPin {
        sha256: sha.clone(),
        content_digest: content.clone(),
    };
    let (loaded, got_sha, got_content) = load_span_head_pinned(&path, 64, &pin).unwrap();
    assert_eq!((got_sha.as_str(), got_content.as_str()), (sha.as_str(), content.as_str()));
    assert_eq!(loaded.named(), head.named());

    let refused = |pin: &HeadInitPin, path: &Path| match load_span_head_pinned(path, 64, pin) {
        Err(TrainError::Refused(m)) => m,
        other => panic!("expected a refusal, got {:?}", other.map(|(_, s, c)| (s, c))),
    };
    let m = refused(&HeadInitPin { sha256: "0".repeat(64), ..pin.clone() }, &path);
    assert!(m.contains("file sha256") && !m.contains("content digest"), "{m}");
    let m = refused(&HeadInitPin { content_digest: "0".repeat(64), ..pin.clone() }, &path);
    assert!(m.contains("content digest") && !m.contains("file sha256"), "{m}");
    // One value changed by one ulp: both digests move, and both are named.
    let mut bumped = tiny_head();
    {
        let (_, v) = &mut bumped.named_mut()[2];
        v[0] = f32::from_bits(v[0].to_bits() + 1);
    }
    let other = dir.join("span_head_init-bumped.safetensors");
    write_head(&other, &bumped);
    let m = refused(&pin, &other);
    assert!(m.contains("file sha256") && m.contains("content digest"), "{m}");
    std::fs::remove_dir_all(&dir).unwrap();
}

/// One of L-oracle's init manifests (`tools/qd_train_oracle_span_head_init.py`).
fn init_manifest(name: &str) -> Value {
    let p = fixtures().join(name);
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))).unwrap()
}

/// Load `path` under `manifest`'s pins through the trainer's loader, and check what the loader
/// recomputed against the manifest, per tensor and over the set.
fn load_under_manifest(path: &Path, manifest: &Value) {
    let hidden = manifest["construction"]["hidden"].as_u64().unwrap() as usize;
    let pin = HeadInitPin {
        sha256: manifest["file"]["sha256"].as_str().unwrap().to_owned(),
        content_digest: manifest["content_digest"]["value"].as_str().unwrap().to_owned(),
    };
    assert_eq!(std::fs::metadata(path).unwrap().len(), manifest["file"]["bytes"].as_u64().unwrap(), "{}", path.display());
    let (head, sha, content) = load_span_head_pinned(path, hidden, &pin).unwrap_or_else(|e| panic!("{e}"));
    assert_eq!((sha.as_str(), content.as_str()), (pin.sha256.as_str(), pin.content_digest.as_str()));
    assert_eq!(head.hidden_size(), hidden);
    // Per tensor: the port's TensorRef.digest of each loaded tensor is the manifest's, where the
    // manifest lists them.
    if let Some(tensors) = manifest["tensors"].as_object() {
        assert_eq!(tensors.len(), 4);
        for (short, values) in head.named() {
            let want = &tensors[&format!("span_head.{short}")];
            let shape: Vec<usize> = want["shape"].as_array().unwrap().iter().map(|d| d.as_u64().unwrap() as usize).collect();
            let bytes: Vec<u8> = values.iter().flat_map(|v| v.to_le_bytes()).collect();
            assert_eq!(tensor_ref_digest("float32", &shape, 4, &bytes).unwrap(), want["digest"].as_str().unwrap(), "{short}");
        }
    }
    // A pin off by one hex digit is refused: the loader is checking, not echoing.
    let mut off = pin.clone();
    off.content_digest.replace_range(0..1, if off.content_digest.starts_with('0') { "1" } else { "0" });
    assert!(matches!(load_span_head_pinned(path, hidden, &off), Err(TrainError::Refused(_))));
}

#[test]
fn l_oracles_tracked_64_wide_init_loads_under_its_manifest_pins() {
    let m = init_manifest("span-head-init-seed0-h64.manifest.json");
    assert_eq!(m["file"]["tracked"], true);
    assert_eq!(m["construction"]["seed"], 0);
    let path = common::repo_root().join(m["file"]["path"].as_str().unwrap());
    load_under_manifest(&path, &m);
    // The same head rung (b)'s init carries, so the same digest the tiny oracle dumped.
    assert_eq!(m["content_digest"]["value"], oracle()["content_digest"]);
}

/// Opt-in: the 2048-wide init is not tracked. Run with
/// `QD_SPAN_HEAD_INIT_2B=<.../data/checkpoints/span-head-init/span_head_init-seed0.safetensors>
/// cargo test -p qd-train --test head_init -- --ignored`.
#[test]
#[ignore = "needs the untracked 2048-wide init file; set QD_SPAN_HEAD_INIT_2B"]
fn the_2048_wide_init_loads_under_its_manifest_pins() {
    let m = init_manifest("span-head-init-seed0.manifest.json");
    assert_eq!(m["file"]["tracked"], false);
    assert_eq!(m["construction"]["hidden"], 2048);
    let Some(path) = std::env::var_os("QD_SPAN_HEAD_INIT_2B") else {
        panic!(
            "QD_SPAN_HEAD_INIT_2B is not set. This test does not pass without the file; point it at \
             the main checkout's {}",
            m["file"]["path"].as_str().unwrap()
        );
    };
    load_under_manifest(Path::new(&path), &m);
}
