"""Generate ``crates/qd-prep/src/pyunicode_tables.rs``: Python's ``\\w`` and ``str.lower()``.

``qd-prep containment`` computes ``qd_train.replay.word_ngrams`` -- ``re.findall(r"\\w+",
text.lower())`` -- in Rust. Rust's ``char::is_alphanumeric`` and ``str::to_lowercase`` are not
that: Rust's ``Alphabetic`` includes ``Other_Alphabetic`` (Devanagari vowel signs, circled
letters) that Python's ``str.isalnum`` excludes, and the two carry different Unicode versions.
So the tables are read off the Python oracle itself, never restated:

* ``WORD``: every code point ``re.fullmatch(r"\\w", ch)`` matches (the regex engine's own
  answer, not a reconstruction from categories);
* ``LOWER``: every code point whose ``ch.lower()`` differs from ``ch``, with its full mapping
  (``"\\u0130".lower()`` is two code points), except U+03A3, which ``lower()`` maps by context;
* ``SIGMA_IGNORABLE`` and ``SIGMA_CASED``: the two classes CPython's ``handle_capital_sigma``
  reads (``_PyUnicode_IsCaseIgnorable``; ``_PyUnicode_IsCased`` and not case-ignorable),
  found by probing ``lower()`` on three strings per code point, because Python exposes
  neither predicate;
* ``UNASSIGNED``: every code point ``unicodedata.category`` calls ``Cn`` in this version. The
  Rust side refuses text containing one: those are the code points whose ``\\w`` and
  ``lower()`` answers a later Unicode version may change.

Surrogates are left out: a ``str`` holding one does not encode to UTF-8, and the containment
request refuses it before Rust sees it.

Usage: ``python tools/qd_prep_unicode_tables.py --out crates/qd-prep/src/pyunicode_tables.rs``
(``--check`` compares instead of writing). Run it with the Python whose ``decontaminate`` is
the oracle; the file records that Python's ``unidata_version``.
"""

from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from collections.abc import Callable, Iterable
from pathlib import Path

SIGMA = 0x03A3
SURROGATES = range(0xD800, 0xE000)
MAX_CODE_POINT = 0x10FFFF
_WORD = re.compile(r"\w")


def code_points() -> Iterable[int]:
    return (c for c in range(MAX_CODE_POINT + 1) if c not in SURROGATES)


def ranges(pred: Callable[[int], bool]) -> list[tuple[int, int]]:
    """Inclusive ``(lo, hi)`` runs of code points satisfying ``pred``, ascending."""
    out: list[tuple[int, int]] = []
    for c in code_points():
        if not pred(c):
            continue
        if out and out[-1][1] == c - 1:
            out[-1] = (out[-1][0], c)
        else:
            out.append((c, c))
    return out


def sigma_class(c: int) -> str:
    """``"ignorable"``, ``"cased"`` (and not ignorable) or ``"other"``, from ``lower()`` alone.

    ``handle_capital_sigma`` walks back from U+03A3 over case-ignorable code points and asks
    whether the first other one is cased; then forward, and asks whether the first other one
    is NOT cased. With ``A`` (cased, not ignorable):

    * ``(c + "Σ").lower()`` ends in final sigma  <=>  c is cased and not ignorable;
    * ``("A" + c + "Σ").lower()`` ends in it     <=>  c is ignorable or cased;
    * ``("AΣ" + c).lower()[1]`` is final sigma   <=>  c is ignorable or not cased.

    Once the first probe has said "not cased-and-not-ignorable", an ignorable code point makes
    the other two true, and any other makes only the third true. Whether an ignorable code
    point is also cased is never read, so it is not needed.
    """
    ch = chr(c)
    if (ch + "Σ").lower()[-1] == "ς":
        return "cased"
    before = ("A" + ch + "Σ").lower()[-1] == "ς"
    after = ("AΣ" + ch).lower()[1] == "ς"
    if before and after:
        return "ignorable"
    if after:
        return "other"
    raise SystemExit(f"U+{c:04X}: lower() probes contradict each other ({before}, {after})")


def lower_map() -> list[tuple[int, list[int]]]:
    out = []
    for c in code_points():
        if c == SIGMA:
            continue
        low = chr(c).lower()
        if low != chr(c):
            if not 1 <= len(low) <= 3:
                raise SystemExit(f"U+{c:04X}.lower() is {len(low)} code points")
            out.append((c, [ord(x) for x in low]))
    return out


def _range_table(name: str, doc: str, rows: list[tuple[int, int]]) -> str:
    body = "\n".join(f"    (0x{lo:04X}, 0x{hi:04X})," for lo, hi in rows)
    return f"/// {doc}\npub(crate) const {name}: &[(u32, u32)] = &[\n{body}\n];\n"


def render() -> str:
    classes = {c: sigma_class(c) for c in code_points()}
    lowers = lower_map()
    lower_rows = "\n".join(
        "    (0x{:04X}, [{}]),".format(
            c, ", ".join(f"0x{x:04X}" for x in m) + ", 0xFFFF_FFFF" * (3 - len(m))
        )
        for c, m in lowers
    )
    parts = [
        "// @generated by tools/qd_prep_unicode_tables.py from CPython's own `re` and",
        f"// `str.lower()`, under Unicode {unicodedata.unidata_version}.",
        "// Do not edit: regenerate, and `python/tests/test_qd_prep_unicode_tables.py` checks",
        "// that the committed file is what the generator writes.",
        "",
        "/// `unicodedata.unidata_version` of the Python the tables were read from.",
        f'pub(crate) const UNIDATA_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
        _range_table("WORD", 'Code points `re.fullmatch(r"\\w", ch)` matches.',
                     ranges(lambda c: _WORD.fullmatch(chr(c)) is not None)),
        "/// `(c, lower(c))` for every code point `lower()` changes but U+03A3; unused slots are",
        "/// `u32::MAX`.",
        "pub(crate) const LOWER: &[(u32, [u32; 3])] = &[",
        lower_rows,
        "];",
        "",
        _range_table("SIGMA_IGNORABLE", "Case-ignorable, as `handle_capital_sigma` skips them.",
                     ranges(lambda c: classes[c] == "ignorable")),
        _range_table("SIGMA_CASED", "Cased and not case-ignorable.",
                     ranges(lambda c: classes[c] == "cased")),
        _range_table("UNASSIGNED", "`unicodedata.category(ch) == \"Cn\"` in this version.",
                     ranges(lambda c: unicodedata.category(chr(c)) == "Cn")),
    ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--check", action="store_true",
                    help="compare with --out instead of writing it; exit 1 on a difference")
    args = ap.parse_args(argv)
    text = render()
    if args.check:
        same = args.out.is_file() and args.out.read_text(encoding="utf-8") == text
        print(f"{args.out}: {'matches' if same else 'DIFFERS from'} the generator under "
              f"Python {sys.version.split()[0]} (Unicode {unicodedata.unidata_version})")
        return 0 if same else 1
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} (Unicode {unicodedata.unidata_version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
